name: Build Manager

on:
  push:
    branches: [ "main", "dev", "ci" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - 'manager/**'
      - 'uapi/**'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - 'manager/**'
      - 'uapi/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build-manager:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manager

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' )) || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            {
              echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
              echo KEY_ALIAS='${{ secrets.KEY_ALIAS }}'
              echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
              echo KEYSTORE_FILE='key.jks'
            } >> gradle.properties
            echo ${{ secrets.KEYSTORE }} | base64 -d > key.jks
          fi

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Build with Gradle
        run: ./gradlew clean assembleRelease

      - name: Upload manager artifact
        uses: actions/upload-artifact@v7
        with:
          name: manager
          path: manager/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Upload APK directly
        uses: actions/upload-artifact@v7
        with:
          name: manager-gradle-apk
          path: |
            manager/app/build/outputs/apk/**/*.apk
            manager/app/build/outputs/**/*.apk
          if-no-files-found: error
